### ISSUE TITLE
Listagem de pedidos

### ISSUE THREAD

**Issue by IcaroBichir** [artmanager/artmanager-mobile#10]
- Os pedidos não estão sendo listados.
- Verificar com o @gustavosk aonde está essa falha

**Comment by ErickWendel** [comment]
esta falha está na api, conforme informado no trello, está retornando o erro: {"error":"Cliente invalido"} (este erro foi reportado no trello e não é erro no aplicativo.)

**Comment by IcaroBichir** [comment]
@gustavosk Dá uma olhada nesse erro

A listagem ainda não está retornando nada
