### ISSUE TITLE
Scroll limitado

### ISSUE THREAD

**Issue by IcaroBichir** [artmanager/artmanager-mobile#11]
- Algumas elas estão com o scroll limitado, tornando impossível selecionar o botão.

<img width="554" alt="screen shot 2016-06-10 at 5 34 27 pm" src="https://cloud.githubusercontent.com/assets/11305787/15977936/abbcc390-2f31-11e6-9401-3c5cb65a7c72.png">

**Comment by ErickWendel** [comment]
Defina "algumas"

**Comment by IcaroBichir** [comment]
- Tela de pedidos
  - Quando mostra os pedidos e tenho opção de incluir mais
  - No resumo do pedido
- Relatório de caixa
