### ISSUE TITLE
Remover peso e altura de TUDO

### ISSUE THREAD

**Issue by IcaroBichir** [artmanager/artmanager-mobile#13]
- Informação completamente irrelevante no produto e ocupa espaço demais na tela

<img width="552" alt="screen shot 2016-06-10 at 5 40 49 pm" src="https://cloud.githubusercontent.com/assets/11305787/15978089/85fd42c8-2f32-11e6-8c6a-d4a8ad9f0f7d.png">

**Comment by ErickWendel** [comment]
defina "tudo"

**Comment by ErickWendel** [comment]
removi somente da tela informada

**Comment by IcaroBichir** [comment]
Pode retirar de tudo, é uma informação desnecessária.
