### ISSUE TITLE
Relatório de Caixa

### ISSUE THREAD

**Issue by IcaroBichir** [artmanager/artmanager-mobile#14]
- Remover comissões
- Scroll não funciona, impossível visualizar relatório completo
- Ordem e nome dos itens:
  - Descontos:
  - Custo total:
  - Total bruto:
  - Total líquido:

<img width="553" alt="screen shot 2016-06-10 at 5 42 41 pm" src="https://cloud.githubusercontent.com/assets/11305787/15978143/c42b125a-2f32-11e6-909f-d48c0c19cf5a.png">

**Comment by IcaroBichir** [comment]
- Falta o valor de custo dos produtos

<img width="538" alt="screen shot 2016-06-13 at 10 36 28 am" src="https://cloud.githubusercontent.com/assets/11305787/16009359/ba67b4e0-3152-11e6-920b-d7c736c1af1a.png">

**Comment by ErickWendel** [comment]
a API nao fornece esse dado!

**Comment by IcaroBichir** [comment]
@gustavosk Precisamos do valor de custo total no relatório de caixa
