### ISSUE TITLE
Dashboard inutilizada totalmente 

### ISSUE THREAD

**Issue by IcaroBichir** [artmanager/artmanager-mobile#16]
- Dashboard está expondo os dados completamente fora do layout.

<img width="550" alt="screen shot 2016-06-13 at 10 24 49 am" src="https://cloud.githubusercontent.com/assets/11305787/16009014/3c5ba972-3151-11e6-80a3-8b19cae5a586.png">

**Comment by ErickWendel** [comment]
o ajuste foi realizado para minha resolução de tela, após a entrega, assim que puder faremos um refactoring e ajustes do layout para funcionar na resolução especificada
