### ISSUE TITLE
Relatório de fornecedor

### ISSUE THREAD

**Issue by IcaroBichir** [artmanager/artmanager-mobile#17]
- Não está trazendo as datas do relatório.

<img width="537" alt="screen shot 2016-06-13 at 10 44 22 am" src="https://cloud.githubusercontent.com/assets/11305787/16009605/dc3111ec-3153-11e6-918f-1283be6aedc2.png">

**Comment by ErickWendel** [comment]
o aplicativo espera esta data, caso não tenha, ele não irá exibir este campo
