### ISSUE TITLE
Nome de produto deletado

### ISSUE THREAD

**Issue by IcaroBichir** [artmanager/artmanager-mobile#5]
- Quando crio fornecedor, o nome do produto é apagado

**Comment by ErickWendel** [comment]
tela de fornecedor ou de pedido ?

**Comment by IcaroBichir** [comment]
Na tela de pedido.
Quando vou fazer o cadastro do fornecedor, ao finalizar o cadastro e retornar para tela de pedido, o nome do produto é apagado.
