### ISSUE TITLE
Nome trazido na dashboard incorreto

### ISSUE THREAD

**Issue by IcaroBichir** [artmanager/artmanager-mobile#9]
- Os novos pedidos estão trazendo o nome do aplicativo. 
- Necessário que traga o nome do cliente e os dados referente ao pedido

**Comment by IcaroBichir** [comment]
<img width="551" alt="screen shot 2016-06-10 at 5 16 35 pm" src="https://cloud.githubusercontent.com/assets/11305787/15977484/68bfac76-2f2f-11e6-9f5d-de7c33b53c42.png">

**Comment by IcaroBichir** [comment]
<img width="543" alt="screen shot 2016-06-10 at 5 35 57 pm" src="https://cloud.githubusercontent.com/assets/11305787/15977979/ea599f10-2f31-11e6-8ce3-9a670401b693.png">

**Comment by ErickWendel** [comment]
o aplicativo envia o id do cliente (testei com 35 e 37) ao salvar pedido e a api está buscando o cliente pelo id, portanto não é um problema no aplicativo.

**Comment by IcaroBichir** [comment]
ok
